// Баррель ASSETS — иконки и изображения с человекочитаемыми именами.
// Импортируй из '@/shared/resources/assets'.
export {
  BrandMarkIcon,
  TableRowsIcon,
  ApiIcon,
  LanguageIcon,
  PlusIcon,
  SearchIcon,
  FilterIcon,
  SaveIcon,
  KeyIcon,
  InboxIcon,
  CloseIcon,
  TrashIcon,
  DotsVerticalIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  SettingsIcon,
  LogoutIcon,
  SparkleIcon,
  UsersIcon,
  HistoryIcon,
  DocIcon,
  HelpIcon,
  EyeIcon,
  EyeOffIcon,
  CheckIcon,
  AlertIcon,
  InfoIcon,
} from './icons';
